/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';

import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';



import { Observable }                                        from 'rxjs';



import { CaseDocument }                                      from '../model/caseDocument';
import { Filter }                                            from '../model/filter';


import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';





@Injectable()


export class CaseDocumentsControllerService {


    protected basePath = 'http://127.0.0.1:3000';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }



    /**
     * 
     * 
     * @param companyID 
     * @param caseID 
     * @param documentID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDFileDelete(companyID: string, caseID: string, documentID: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDFileDelete(companyID: string, caseID: string, documentID: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDFileDelete(companyID: string, caseID: string, documentID: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDFileDelete(companyID: string, caseID: string, documentID: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (companyID === null || companyID === undefined) {
            throw new Error('Required parameter companyID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsDocumentIDFileDelete.');
        }
        if (caseID === null || caseID === undefined) {
            throw new Error('Required parameter caseID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsDocumentIDFileDelete.');
        }
        if (documentID === null || documentID === undefined) {
            throw new Error('Required parameter documentID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsDocumentIDFileDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete(`${this.basePath}/companies/${encodeURIComponent(String(companyID))}/cases/${encodeURIComponent(String(caseID))}/documents/${encodeURIComponent(String(documentID))}/file`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }


    /**
     * 
     * 
     * @param companyID 
     * @param caseID 
     * @param documentID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDFileGet(companyID: string, caseID: string, documentID: string, archivedCase?: boolean, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDFileGet(companyID: string, caseID: string, documentID: string, archivedCase?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDFileGet(companyID: string, caseID: string, documentID: string, archivedCase?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDFileGet(companyID: string, caseID: string, documentID: string, archivedCase: boolean = false, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (companyID === null || companyID === undefined) {
            throw new Error('Required parameter companyID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsDocumentIDFileGet.');
        }
        if (caseID === null || caseID === undefined) {
            throw new Error('Required parameter caseID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsDocumentIDFileGet.');
        }
        if (documentID === null || documentID === undefined) {
            throw new Error('Required parameter documentID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsDocumentIDFileGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        queryParameters = queryParameters.append('archivedCase', archivedCase.toString());

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [];

        return this.httpClient.get(`${this.basePath}/companies/${encodeURIComponent(String(companyID))}/cases/${encodeURIComponent(String(caseID))}/documents/${encodeURIComponent(String(documentID))}/file`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                responseType: 'blob',
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }


    /**
     * 
     * 
     * @param companyID 
     * @param caseID 
     * @param documentID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDGet(companyID: string, caseID: string, documentID: string, observe?: 'body', reportProgress?: boolean): Observable<CaseDocument>;
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDGet(companyID: string, caseID: string, documentID: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CaseDocument>>;
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDGet(companyID: string, caseID: string, documentID: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CaseDocument>>;
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDGet(companyID: string, caseID: string, documentID: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (companyID === null || companyID === undefined) {
            throw new Error('Required parameter companyID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsDocumentIDGet.');
        }
        if (caseID === null || caseID === undefined) {
            throw new Error('Required parameter caseID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsDocumentIDGet.');
        }
        if (documentID === null || documentID === undefined) {
            throw new Error('Required parameter documentID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsDocumentIDGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get(`${this.basePath}/companies/${encodeURIComponent(String(companyID))}/cases/${encodeURIComponent(String(caseID))}/documents/${encodeURIComponent(String(documentID))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param companyID 
     * @param caseID 
     * @param documentID 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDPatch(companyID: string, caseID: string, documentID: string, body?: CaseDocument, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDPatch(companyID: string, caseID: string, documentID: string, body?: CaseDocument, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDPatch(companyID: string, caseID: string, documentID: string, body?: CaseDocument, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public companiesCompanyIDCasesCaseIDDocumentsDocumentIDPatch(companyID: string, caseID: string, documentID: string, body?: CaseDocument, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (companyID === null || companyID === undefined) {
            throw new Error('Required parameter companyID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsDocumentIDPatch.');
        }
        if (caseID === null || caseID === undefined) {
            throw new Error('Required parameter caseID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsDocumentIDPatch.');
        }
        if (documentID === null || documentID === undefined) {
            throw new Error('Required parameter documentID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsDocumentIDPatch.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.patch(`${this.basePath}/companies/${encodeURIComponent(String(companyID))}/cases/${encodeURIComponent(String(caseID))}/documents/${encodeURIComponent(String(documentID))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param companyID 
     * @param caseID 
     * @param filter 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companiesCompanyIDCasesCaseIDDocumentsGet(companyID: string, caseID: string, filter?: Filter, observe?: 'body', reportProgress?: boolean): Observable<Array<CaseDocument>>;
    public companiesCompanyIDCasesCaseIDDocumentsGet(companyID: string, caseID: string, filter?: Filter, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CaseDocument>>>;
    public companiesCompanyIDCasesCaseIDDocumentsGet(companyID: string, caseID: string, filter?: Filter, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CaseDocument>>>;
    public companiesCompanyIDCasesCaseIDDocumentsGet(companyID: string, caseID: string, filter?: Filter, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (companyID === null || companyID === undefined) {
            throw new Error('Required parameter companyID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsGet.');
        }
        if (caseID === null || caseID === undefined) {
            throw new Error('Required parameter caseID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (filter !== undefined && filter !== null) {
            queryParameters = queryParameters.set('filter', JSON.stringify(filter));
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get(`${this.basePath}/companies/${encodeURIComponent(String(companyID))}/cases/${encodeURIComponent(String(caseID))}/documents`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param companyID 
     * @param caseID 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companiesCompanyIDCasesCaseIDDocumentsPost(companyID: string, caseID: string, body?: CaseDocument, observe?: 'body', reportProgress?: boolean): Observable<CaseDocument>;
    public companiesCompanyIDCasesCaseIDDocumentsPost(companyID: string, caseID: string, body?: CaseDocument, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CaseDocument>>;
    public companiesCompanyIDCasesCaseIDDocumentsPost(companyID: string, caseID: string, body?: CaseDocument, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CaseDocument>>;
    public companiesCompanyIDCasesCaseIDDocumentsPost(companyID: string, caseID: string, body?: CaseDocument, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (companyID === null || companyID === undefined) {
            throw new Error('Required parameter companyID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsPost.');
        }
        if (caseID === null || caseID === undefined) {
            throw new Error('Required parameter caseID was null or undefined when calling companiesCompanyIDCasesCaseIDDocumentsPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post(`${this.basePath}/companies/${encodeURIComponent(String(companyID))}/cases/${encodeURIComponent(String(caseID))}/documents`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }




}
