/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable, from }                                        from 'rxjs';

import { CompanyCase } from '../model/companyCase';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CompanyCasesControllerService {

    protected basePath = 'http://127.0.0.1:3000';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }



    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */    
    public getUnpaidEscortCases(observe?: 'body', reportProgress?: boolean): Observable<Array<CompanyCase>>;
    public getUnpaidEscortCases(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CompanyCase>>>;
    public getUnpaidEscortCases(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CompanyCase>>>;
    public getUnpaidEscortCases(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
            
        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    
        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [ 'application/json' ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }
        
        const consumes: string[] = [ ];

        return this.httpClient.get(`${this.basePath}/companies/UNDEFINED/cases/UNDEFINED/unpaidEscorts`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }



    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */    
    public getCaseReceivables(observe?: 'body', reportProgress?: boolean): Observable<Array<CompanyCase>>;
    public getCaseReceivables(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CompanyCase>>>;
    public getCaseReceivables(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CompanyCase>>>;
    public getCaseReceivables(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
            
        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    
        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [ 'application/json' ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }
        
        const consumes: string[] = [ ];

        return this.httpClient.get(`${this.basePath}/companies/UNDEFINED/unpaidCases`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }



    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */    
    public getArchivedCases(observe?: 'body', reportProgress?: boolean): Observable<Array<CompanyCase>>;
    public getArchivedCases(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CompanyCase>>>;
    public getArchivedCases(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CompanyCase>>>;
    public getArchivedCases(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
            
        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    
        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [ 'application/json' ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }
        
        const consumes: string[] = [ ];

        return this.httpClient.get(`${this.basePath}/companies/UNDEFINED/archivedCases`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }



    /**
     * 
     * 
     * @param caseID
     * @param escortID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */    
    public markCaseEscortPaid(caseID : string, escortID : string, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public markCaseEscortPaid(caseID : string, escortID : string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public markCaseEscortPaid(caseID : string, escortID : string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public markCaseEscortPaid(caseID : string, escortID : string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (caseID === null || caseID === undefined || caseID.trim().length == 0) {
            throw new Error('Required parameter caseID was null or undefined when calling markCaseEscortPaid.');
        }
        if (escortID === null || escortID === undefined || escortID.trim().length == 0) {
            throw new Error('Required parameter escortID was null or undefined when calling markCaseEscortPaid.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [ 'application/json' ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }
        
        // to determine the Content-Type header
        const consumes: string[] = [ 'application/json' ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post(`${this.basePath}/companies/UNDEFINED/cases/${encodeURIComponent(String(caseID))}/unpaidEscorts/${encodeURIComponent(String(escortID))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }



    /**
     * 
     * 
     * @param caseID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */    
    public markCasePaid(caseID : string, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public markCasePaid(caseID : string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public markCasePaid(caseID : string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public markCasePaid(caseID : string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (caseID === null || caseID === undefined || caseID.trim().length == 0) {
            throw new Error('Required parameter caseID was null or undefined when calling markCasePaid.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [ 'application/json' ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }
        
        // to determine the Content-Type header
        const consumes: string[] = [ 'application/json' ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post(`${this.basePath}/companies/UNDEFINED/unpaidCases/${encodeURIComponent(String(caseID))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }




    /**
     * 
     * @param companyID
     * @param filter 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */    
    public companyCasesGet(filter?: any, companyID?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<CompanyCase>>;
    public companyCasesGet(filter?: any, companyID?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CompanyCase>>>;
    public companyCasesGet(filter?: any, companyID?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CompanyCase>>>;
    public companyCasesGet(filter?: any, companyID?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (companyID === null || companyID === undefined) { companyID = 'UNKNOWN'; }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    
        if (filter !== undefined && filter !== null) {
            queryParameters = queryParameters.set('filter', <any>filter);        
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [ 'application/json' ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }
        
        const consumes: string[] = [ ];

        return this.httpClient.get(`${this.basePath}/companies/${encodeURIComponent(String(companyID))}/cases`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }




    /**
     * 
     * 
     * @param companyID 
     * @param caseID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companiesCompanyIDCasesCaseIDGet(companyID: string, caseID: string, observe?: 'body', reportProgress?: boolean): Observable<CompanyCase>;
    public companiesCompanyIDCasesCaseIDGet(companyID: string, caseID: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CompanyCase>>;
    public companiesCompanyIDCasesCaseIDGet(companyID: string, caseID: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CompanyCase>>;
    public companiesCompanyIDCasesCaseIDGet(companyID: string, caseID: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (companyID === null || companyID === undefined) {
            throw new Error('Required parameter companyID was null or undefined when calling companiesCompanyIDCasesCaseIDGet.');
        }
        if (caseID === null || caseID === undefined) {
            throw new Error('Required parameter caseID was null or undefined when calling companiesCompanyIDCasesCaseIDGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get(`${this.basePath}/companies/${encodeURIComponent(String(companyID))}/cases/${encodeURIComponent(String(caseID))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }



    /**
     * 
     * 
     * @param externalAccessID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public publicCasesExternalAccessIDGet(externalAccessID: string, observe?: 'body', reportProgress?: boolean): Observable<CompanyCase>;
    public publicCasesExternalAccessIDGet(externalAccessID: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CompanyCase>>;
    public publicCasesExternalAccessIDGet(externalAccessID: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CompanyCase>>;
    public publicCasesExternalAccessIDGet(externalAccessID: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (externalAccessID === null || externalAccessID === undefined) {
            throw new Error('Required parameter externalAccessID was null or undefined when calling publicCasesExternalAccessIDGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [];

        return this.httpClient.get(`${this.basePath}/publicCases/${encodeURIComponent(String(externalAccessID))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }



    /**
     * 
     * 
     * @param companyID 
     * @param caseID 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companiesCompanyIDCasesCaseIDPatch(companyID: string, caseID: string, body?: CompanyCase, sendEmail? : boolean, emailComments? : string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public companiesCompanyIDCasesCaseIDPatch(companyID: string, caseID: string, body?: CompanyCase, sendEmail? : boolean, emailComments? : string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public companiesCompanyIDCasesCaseIDPatch(companyID: string, caseID: string, body?: CompanyCase, sendEmail? : boolean, emailComments? : string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public companiesCompanyIDCasesCaseIDPatch(companyID: string, caseID: string, body?: CompanyCase, sendEmail? : boolean, emailComments? : string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (companyID === null || companyID === undefined) {
            throw new Error('Required parameter companyID was null or undefined when calling companiesCompanyIDCasesCaseIDPatch.');
        }
        if (caseID === null || caseID === undefined) {
            throw new Error('Required parameter caseID was null or undefined when calling companiesCompanyIDCasesCaseIDPatch.');
        }

        // Assemble the URL and the Request
        let url : string = `${this.basePath}/companies/${encodeURIComponent(String(companyID))}/cases/${encodeURIComponent(String(caseID))}`;
        if (sendEmail !== undefined && sendEmail !== null && sendEmail == true) {
            url = url + `?sendEmail=${sendEmail}`; 
            if (emailComments !== undefined && emailComments !== null) {
                url = url + `&emailComments=${emailComments}`;        
            }       
        }

        let requestInit : RequestInit = {
            method: 'PATCH',
            headers: new Headers({
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }),
            body: JSON.stringify(body)
        };

        // Send the request and package the response as an Observable
        return from(fetch(url, requestInit)
                    .then((response)=>{
                        if (response.ok) {
                            // HTTP PATCH will not return anything (204 - No Content), so return true
                            return true;
                        }
                        console.log(response);
                        throw new Error('The response was not ok');
                    })
        );
    }




    /**
     * 
     * 
     * @param companyID 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public companiesCompanyIDCasesPost(companyID: string, body?: CompanyCase, observe?: 'body', reportProgress?: boolean): Observable<CompanyCase>;
    public companiesCompanyIDCasesPost(companyID: string, body?: CompanyCase, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CompanyCase>>;
    public companiesCompanyIDCasesPost(companyID: string, body?: CompanyCase, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CompanyCase>>;
    public companiesCompanyIDCasesPost(companyID: string, body?: CompanyCase, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (companyID === null || companyID === undefined) {
            throw new Error('Required parameter companyID was null or undefined when calling companiesCompanyIDCasesPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post(`${this.basePath}/companies/${encodeURIComponent(String(companyID))}/cases`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }



}
